### ISSUE TITLE
Use video-id instead of the full URL

### ISSUE THREAD

**Issue by nostadt** [liquidlight/typo3-shortcodes#10]
### Summary / problem to solve

Currently the full URL has to be used. If there is no space between the URL and closing `]` and you hit `space`, or just `enter` the CKEditor  will make the URL clickable and therefore the parsing does not work anymore.

**Example**

```
[vimeo: https://vimeo.com/397673759]
```
Now, when placing the cursor **after** `]` followed by pressing  `space` you will receive the following result:

![typo3-shortcode-example](https://user-images.githubusercontent.com/5464339/159708399-ae0ba516-4635-409e-816c-f2764ab60c32.png)

And here's the `HTML` that will be generated:

```html
<p>[vimeo: <a href="https://vimeo.com/397673759]">https://vimeo.com/397673759]</a>&nbsp;</p>
```

In FE it looks like this:

![image](https://user-images.githubusercontent.com/5464339/159709160-e750ff72-15e8-4ef2-bb87-9ea59a07b638.png)

**Instead I suggest following:**

_In my setup it worked fine._

```
[vimeo: 397673759]
```

Of course the URL will need to be provided in the PHP class that takes care of the replacement.

### Specific project use-cases

_Any kind of project IMO._

### Blockers

_Not that I can think of._

### More details, logs and/or screenshots

TYPO3 version: v10

typo3-shortcodes: v1.2.2

**Comment by nostadt** [comment]
To avoid BC, the video-id could be configured as an additional allowed value.

**Comment by nostadt** [comment]
Oh, this actually works already.

**Comment by mikestreety** [comment]
@nostadt Hey, i'm so sorry I missed this, i don't seem to have notifications turned on - glad you figured it out & i'm so happy to see someone else using it!

**Comment by mikestreety** [comment]
@nostadt If they do want to paste the URL, they just need to make sure there is a space between that and the `]` - the shortcodes EXT will strip the A tag and process the URL as expected (see the "Usage" section ⚠️ - https://github.com/liquidlight/typo3-shortcodes#usage )
