### ISSUE TITLE
Bring the PHP 8 branch into the main branch

### ISSUE THREAD

**Issue by Kephson** [liquidlight/typo3-shortcodes#21]
To have this extension work with PHP >= 8.0 please bring your PHP 8 branch into the main branch.

**Comment by mikestreety** [comment]
Hey, thanks for request - we haven't actually had much time to test it, are you able to confirm it works as expected?

**Comment by Kephson** [comment]
Hi, thanks for your reply; yes it works as expected, but I tested it together with the PHP 8 branch with TYPO3 11.5.

**Comment by mikestreety** [comment]
Ok great, we'll do a couple more tests to make sure it doesn't break anything existing our end 👍 It'll be released in the next few (working) days

**Comment by Kephson** [comment]
From my side it works as expected.

**Comment by mikestreety** [comment]
All merged. will release next week

**Comment by Kephson** [comment]
No problem ;-)
