### ISSUE TITLE
TYPO3 v12 compatibilty

### ISSUE THREAD

**Issue by mathias-heilmann** [liquidlight/typo3-shortcodes#25]
Hi!

Do you have any plans on making your extension v12 compatible?

**Comment by mikestreety** [comment]
Hi @mathias-heilmann,

Not in the immediate future but it is on the roadmap - we're just not sure when we can get to it.

There might be a slim chance that it "Just Works™️", but I suspect some refactoring may be required as we'll want to drop 9 & 10 at the same time

**Comment by mathias-heilmann** [comment]
Its very easy, just change the 

`defined('TYPO3_MODE') or die();`

to

`defined('TYPO3') or die();`

in the [ext_localconf.php](https://github.com/liquidlight/typo3-shortcodes/blob/main/ext_localconf.php)

**Comment by mikestreety** [comment]
@mathias-heilmann Is that all that is needed? I'll get a branch up so it can be tested. Thanks!

**Comment by mathias-heilmann** [comment]
Yes, I have testet the compatibility with the upgrade tool and it was all green.

**Comment by mikestreety** [comment]
@mathias-heilmann I've pushed to main with the change :)

**Comment by mikestreety** [comment]
@mathias-heilmann Sorry for the mega-delay!

v2.0.0 has just been published with v11 & 12 compat and dropping v9 & v10
