### ISSUE TITLE
Create a WYSIWYG insert drop down

### ISSUE THREAD

**Issue by mikestreety** [liquidlight/typo3-shortcodes#6]
### Summary of task

Is there a way we can add a new toolbar item to the WYSIWYG/RTE to create an "Insert shortcode" item - which lists all the available shortcodes.

### More details, logs and/or screenshots

Prototype can just insert the shortcode into the text `[youtube url=""]`

More advance could pop up and have fields for each of the properties

**Comment by moe2k** [comment]
Maybe this helps: https://ckeditor.com/docs/ckeditor4/latest/examples/placeholder.html
